### ISSUE TITLE
Problem with agreement display based on PII selection

### ISSUE THREAD

**Issue by markmcelhaw** [researchops/consentform#5]
the agreement is vertically displaying  a personal information selection on the agreements with as alist of bullets.  Think its because I selected personal information to be recorded.  @Gorpalicious   FYI this is a test of a complete newbie trying to log an issue.  Phil made me do this. 
<img width="952" alt="Screenshot 2020-08-19 at 12 11 44" src="https://user-images.githubusercontent.com/56116033/90688052-c56c3a00-e265-11ea-8480-f8432b3b83af.png">

**Comment by designbuddy** [comment]
Fixed
